// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD7Y3w-2IjrNajVrwSO_w7amxZ9ql4x-4',
    appId: '1:732696899318:web:8c0b7c3fd2ea06312a86d7',
    messagingSenderId: '732696899318',
    projectId: 'suppliers-c8b5a',
    authDomain: 'suppliers-c8b5a.firebaseapp.com',
    storageBucket: 'suppliers-c8b5a.appspot.com',
    measurementId: 'G-DC8SVMJDFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9nU8bQXqotG6UUxWfNkhTl5mzsZWtr78',
    appId: '1:732696899318:android:0ed93e429a070fd32a86d7',
    messagingSenderId: '732696899318',
    projectId: 'suppliers-c8b5a',
    storageBucket: 'suppliers-c8b5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlYh6VUs5U4u4uffLHa9WYDKpL6uicWEM',
    appId: '1:732696899318:ios:714776e37dea2f782a86d7',
    messagingSenderId: '732696899318',
    projectId: 'suppliers-c8b5a',
    storageBucket: 'suppliers-c8b5a.appspot.com',
    iosBundleId: 'com.example.mufratyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlYh6VUs5U4u4uffLHa9WYDKpL6uicWEM',
    appId: '1:732696899318:ios:714776e37dea2f782a86d7',
    messagingSenderId: '732696899318',
    projectId: 'suppliers-c8b5a',
    storageBucket: 'suppliers-c8b5a.appspot.com',
    iosBundleId: 'com.example.mufratyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD7Y3w-2IjrNajVrwSO_w7amxZ9ql4x-4',
    appId: '1:732696899318:web:0caf7c57729a995e2a86d7',
    messagingSenderId: '732696899318',
    projectId: 'suppliers-c8b5a',
    authDomain: 'suppliers-c8b5a.firebaseapp.com',
    storageBucket: 'suppliers-c8b5a.appspot.com',
    measurementId: 'G-WLZJBYB9Y7',
  );
}
